version: "3.2"
services:
  zero:
    image: dgraph/dgraph:stable
    volumes:
      - ./data:/dgraph
    ports:
      - "127.0.0.1:5080:5080"
      - "127.0.0.1:6080:6080"
    restart: always
    command: dgraph zero --my=zero:5080

  server:
    image: dgraph/dgraph:stable
    volumes:
      - ./data:/dgraph
    ports:
      - "127.0.0.1:8080:8080"
      - "9080:9080"
    restart: always
    command: dgraph server --my=server:7080 --lru_mb=2048 --zero=zero:5080

  xcamp:
    build: .
    ports:
      - "127.0.0.1:8010:3000"
    links:
      - server
    environment:
      - PORT=3000
      - AUTH_SECRET=f1/dds;2fklj§r6,e!4.o8!eio
      - BASEURL=https://xcamp.co/netvis/
      - NODE_ENV=production
      - DGRAPH_URL=server:9080
      - SMTP_HOST=172.20.0.1
    volumes:
      - ./profile-pictures:/app/profile-pictures
    restart: always
